### ISSUE TITLE
Misplaced space in file_access_godot3.gd script.

### ISSUE THREAD

**Issue by Majniaki** [daveTheOldCoder/Godot3To4FileConversion#1]
**Describe the bug**
In the function: func _convert_variable() -> void: in file_access_godot3.gd at line 205 there is a misplaced space and it gives an error.

**To Reproduce**
-
**Expected behavior**
-
**Screenshots**
-
**Desktop (please complete the following information):**
 - OS: MacOS
 - Godot 4.1.1.

**Comment by daveTheOldCoder** [comment]
Thanks for the report. This has been fixed by commit https://github.com/daveTheOldCoder/Godot3To4FileConversion/commit/67674b57fc4fdab79b1d02800c6b95b9ecfaf2c5
