### ISSUE TITLE
Update example 2 in the docs

### ISSUE THREAD

**Issue by Majniaki** [daveTheOldCoder/Godot3To4FileConversion#2]
in example 2 in the docs there shouldn't be any parameters in the brackets.

should be:
var i: int = file_g3.get_var()
var f: float = file.get_float()
var s: String = file_g3.get_var()
var j: int = file.get_32()
var a: Array = file_g3.get_var()
var d: Dictionary = file_g3.get_var()

not:
var i: int = file_g3.get_var()
var f: float = file.get_float()
var s: String = file_g3.get_var()
var j: int = file.get_32()
var a: Array = file_g3.get_var(a)
var d: Dictionary = file_g3.get_var(d)

**Comment by daveTheOldCoder** [comment]
Thanks! This has been fixed by commit https://github.com/daveTheOldCoder/Godot3To4FileConversion/commit/5ce45479cc16c076154dd6cb70cd7e31ca9390b8
